Merge releases/m71 to master
webrtc-uwp/webrtc-uwp.github.io pull request #9
Opened 2019-04-29 16:26 UTC by jamescadd

Documentation is now complete enough for a first pass and ready to be merged to master for publication.

2019-04-29 17:26 UTC, robin-raymond requested changes

2019-04-29 17:26 UTC, robin-raymond commented on how-to-audio-processing.md
> +    var array = data.Data.ToArray();
var array = new Int16[data.Length];
            data.GetData(array);

2019-04-29 17:26 UTC, robin-raymond commented on how-to-audio-processing.md
> +    data.Data = array;
data.SetData(dataArray);

2019-04-29 17:51 UTC, jamescadd commented on how-to-audio-processing.md
> +    var array = data.Data.ToArray();
Good catch, corrected.

2019-04-29 17:51 UTC, jamescadd commented on how-to-audio-processing.md
> +    data.Data = array;
Same

2019-04-29 17:55 UTC, robin-raymond approved these changes

2019-04-29 17:56 UTC, merged

2024-01-23 22:27 UTC, Joshua9115 commented on azure-devops-build.md
> +https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=new-nav#create-a-feed
good

2024-01-23 22:27 UTC, Joshua9115 commented on how-to-audio-device-selection.md
> +# Audio device enumeration and selection
my name

2024-01-23 22:28 UTC, Joshua9115 commented on how-to-audio-device-selection.md
> +The following code from the `MainViewModel.cs` file of the `PeerCC` sample demonstrates enumeration & setting of capture and render devices:
atlerviper

2024-01-23 22:29 UTC, Joshua9115 commented on how-to-audio-device-selection.md
> +The following code from the `MainViewModel.cs` file of the `PeerCC` sample demonstrates enumeration & setting of capture and render devices:
ATLERVIPER

2024-01-23 22:30 UTC, Joshua9115 reviewed
Thank you